export const authAppearance = {
  variables: {
    colorPrimary: "#ff8a00",
    colorBackground: "#111111",
    colorText: "#fafafa",
    colorTextSecondary: "#a1a1aa",
    colorInputBackground: "#1b1b1d",
    colorInputText: "#fafafa",
    borderRadius: "10px",
  },
  elements: {
    rootBox: "auth-clerk-root",
    cardBox: "auth-clerk-box",
    card: "auth-clerk-card",
    header: "mb-2!",
    logoImage: "hidden",
    headerTitle: "text-xl!",
    headerSubtitle: "text-xs!",
    socialButtonsBlock: "gap-2!",
    socialButtonsBlockButton: "min-h-9! py-1.5! text-sm!",
    dividerRow: "my-2.5!",
    formFieldRow: "mb-1.5!",
    formFieldLabel: "mb-0.5! text-xs!",
    formFieldInput: "h-9! text-sm!",
    formButtonPrimary: "min-h-9! py-1.5! text-sm!",
    footer: "auth-clerk-footer mt-2! py-1.5! text-xs!",
    footerAction: "mt-0!",
  },
} as const;
